/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'doctorId' : IDL.Nat,
  'deleted' : IDL.Bool,
  'patientId' : IDL.Nat,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'lastUpdate' : Time,
  'notes' : IDL.Text,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'patientIds' : IDL.Vec(IDL.Nat),
  'deleted' : IDL.Bool,
  'name' : IDL.Text,
  'lastUpdate' : Time,
  'availability' : IDL.Bool,
  'specialization' : IDL.Text,
  'department' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'deleted' : IDL.Bool,
  'contact' : IDL.Text,
  'admissionDate' : IDL.Text,
  'name' : IDL.Text,
  'treatment' : IDL.Text,
  'lastUpdate' : Time,
  'gender' : IDL.Text,
  'disease' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardTotals = IDL.Record({
  'totalPatients' : IDL.Nat,
  'todaysAppointments' : IDL.Nat,
  'totalDoctors' : IDL.Nat,
  'totalAppointments' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
  'createAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
  'createDoctor' : IDL.Func([Doctor], [IDL.Nat], []),
  'createPatient' : IDL.Func([Patient], [IDL.Nat], []),
  'deleteDoctor' : IDL.Func([IDL.Nat], [], []),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'getAdmissionsByDate' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAppointmentsByDoctor' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardTotals' : IDL.Func([IDL.Text], [DashboardTotals], ['query']),
  'getDiseaseFrequency' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getDoctorAppointmentCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'readDoctor' : IDL.Func([IDL.Nat], [Doctor], []),
  'readPatient' : IDL.Func([IDL.Nat], [Patient], []),
  'rescheduleAppointment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDoctor' : IDL.Func([Doctor], [], []),
  'updatePatient' : IDL.Func([Patient], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'doctorId' : IDL.Nat,
    'deleted' : IDL.Bool,
    'patientId' : IDL.Nat,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'lastUpdate' : Time,
    'notes' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'patientIds' : IDL.Vec(IDL.Nat),
    'deleted' : IDL.Bool,
    'name' : IDL.Text,
    'lastUpdate' : Time,
    'availability' : IDL.Bool,
    'specialization' : IDL.Text,
    'department' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'deleted' : IDL.Bool,
    'contact' : IDL.Text,
    'admissionDate' : IDL.Text,
    'name' : IDL.Text,
    'treatment' : IDL.Text,
    'lastUpdate' : Time,
    'gender' : IDL.Text,
    'disease' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardTotals = IDL.Record({
    'totalPatients' : IDL.Nat,
    'todaysAppointments' : IDL.Nat,
    'totalDoctors' : IDL.Nat,
    'totalAppointments' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
    'createAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
    'createDoctor' : IDL.Func([Doctor], [IDL.Nat], []),
    'createPatient' : IDL.Func([Patient], [IDL.Nat], []),
    'deleteDoctor' : IDL.Func([IDL.Nat], [], []),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'getAdmissionsByDate' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAppointmentsByDoctor' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardTotals' : IDL.Func([IDL.Text], [DashboardTotals], ['query']),
    'getDiseaseFrequency' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getDoctorAppointmentCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'readDoctor' : IDL.Func([IDL.Nat], [Doctor], []),
    'readPatient' : IDL.Func([IDL.Nat], [Patient], []),
    'rescheduleAppointment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDoctor' : IDL.Func([Doctor], [], []),
    'updatePatient' : IDL.Func([Patient], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
